// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "d74fd968-36d1-4f9c-b9d0-687cbc6c11e4";

const char SSID[]               = "Railwire_Internet";    // Network SSID (name)
const char PASS[]               = "atomwork";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "!YHBO8C#MBErs7D686OLtgRpO";    // Secret device password

void onButtonChange();

bool button;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(button, READWRITE, ON_CHANGE, onButtonChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
